### PR TITLE
LightGraphs support

### PR DESCRIPTION
**Pull request by sbromberger**
example:
```
import "src/Hargreaves.jl"
using LightGraphs, Hargreaves

g = CompleteGraph(41)
wireplot(g)
```
yielding

wireplot

### CODE REVIEW

**Comment by sbromberger** [comment]
PS: if this works for you, you might consider dropping the other function(s). That way your REQUIRES can eliminate DataFrames.

**Comment by antonhinneck** [comment]
Thanks for supervising the code. This helps a lot. I will keep it this clean :) I plan to make first changes mid week when I have some free time on the evening.

I looked into LightGraphs.jl a little more and haven't found a weight or cost property of edges. 
If vertices represent cities for example, the distance between two cities c1 and c2 could be stored as a property of the edge e1(c1,c2). I could work around it by using Dict{e::SimpleEdge,Float64}(). Then however the mere input of a SimpleGraph wouldn't be enough. I would also need pass this data separately to the plotting function. Did I overlook something?

**Comment by sbromberger** [comment]
> I looked into LightGraphs.jl a little more and haven't found a weight or cost property of edges.

Take a look at [SimpleWeightedGraphs.jl](https://github.com/JuliaGraphs/SimpleWeightedGraphs.jl) or [MetaGraphs.jl](https://github.com/JuliaGraphs/MetaGraphs.jl) for graphs with built-in weights. Otherwise, just keep an external Dict as you suggest that associates edge to weight, and override `weights()`

**Comment by sbromberger** [comment]
PS: I just made a version that works only with LightGraphs (I got rid of the generic arrays) and takes weights using the standard LG convention. It's at https://github.com/sbromberger/Hargreaves.jl/tree/sbromberger/lg-only.

If you like this and want to move forward with it, let me know and I'll submit it as a PR. Otherwise, if you want to keep your package more generic (using arrays), that's perfectly cool too and I'll probably create an LG-only recipe based on your code (with credit, of course).

**Comment by antonhinneck** [comment]
Yes, a new PR would be good. Everything I implemented to store graphs is just a very primitive version of what is implemented in LightGraphs anyways. Only having a graph object is much more elegant. I will then merge the new PR once I worked through it (I need this plot for my master thesis on production scheduling using mixed integer programming). Sorry for the delayed responses, I am from Berlin. Once you created a new PR, can I close this one?

**Comment by antonhinneck** [comment]
Support moved to **Sbromberger/lg only #2**

**Comment by sbromberger** [comment]
Yes - that sounds great. Thanks for considering my updates.

When #2 gets merged, would you like to move it into JuliaGraphs and become an organization member? (You'd still have full control over your repo, but it would be under the JuliaGraphs umbrella to make it easier for folks to find/use it.)

**Comment by antonhinneck** [comment]
Yes, of course :) I think the end of this week is realistic, there is a lot in LightGraphs to get familiar with.

**Comment by sbromberger** [comment]
No rush. Let me know if you have any questions about the PR or LightGraphs in general. You can open up issues on LG, or find us in #graphs on slack.

**Pull request closed without merging**
